### ISSUE TITLE
Error when searching in popup report

### ISSUE THREAD

**Issue by eseisd** [bostrowski/APEX-Enhanced-Lov-Item#2]
I've installed the plugin and package files and added the item to my page.  Everything appears to be working until I try to search within the popup report.  I type in my search term and press enter, and then I get the following error:

**_is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -907
ora_sqlerrm: ORA-00907: missing right parenthesis
component.type: APEX_APPLICATION_PAGE_ITEMS
component.id: 15569109621496658
component.name: P30_SUPPLIER_LOV
error_backtrace: ORA-06512: at "SYS.DBMS_SQL", line 1120
ORA-06512: at "APEX_EBA.APEX_ENHANCED_LOV_ITEM", line 55
ORA-06512: at "APEX_EBA.APEX_ENHANCED_LOV_ITEM", line 808
ORA-06512: at "APEX_EBA.APEX_ENHANCED_LOV_ITEM", line 1074
ORA-06512: at line 4
ORA-06512: at "SYS.DBMS_SQL", line 1707
ORA-06512: at "APEX_180200.WWV_FLOW_DYNAMIC_EXEC", line 2450
ORA-06512: at "APEX_180200.WWV_FLOW_DYNAMIC_EXEC", line 1476
ORA-06512: at "APEX_180200.WWV_FLOW_PLUGIN", line 1312

error_statement: begin declare

begin
APEX_EBA.APEX_ENHANCED_LOV_ITEM.ajax (p_plugin => wwv_flow_plugin_api.g_plugin,p_item => wwv_flow_plugin_api.g_item,p_param => wwv_flow_plugin_api.g_item_ajax_param,p_result => wwv_flow_plugin_api.g_item_ajax_result );end;
end;_**

Am I missing something with the installation process?  I'm running APEX 18.2.

I will attach a screenshot showing my settings on the item:  ![APEX Enhanced LOV Settings](https://user-images.githubusercontent.com/15090140/55968365-dbb5bf00-5c49-11e9-9036-ba3c47655896.jpg)

Here is the Report Columns Configuration code I'm using:

{
  "defaultSort": {
    "column": "Supplier Name",
    "direction": "asc"
  },
  "columns": {
    "Supplier Name": {
      "visible": true,
      "heading": "Supplier Name",
      "thAlign": "left",
      "tdAlign": "left",
      "sort": true,
      "filter": true
    }, 
    "Site": {
      "visible": true,
      "heading": "Site",
      "thAlign": "left",
      "tdAlign": "left",
      "sort": false,
      "filter": false
    }, 
    "Address": {
      "visible": true,
      "heading": "Address",
      "thAlign": "left",
      "tdAlign": "left",
      "sort": false,
      "filter": false
    }    
  }
}

Thanks for your help.

-Eric

**Comment by bostrowski** [comment]
@eseisd 
We have exchanged e-mail regarding the issue. The problem was column aliases in quote characters. The plugin doesn't support aliases in quotes (also it can break if inline comments "--" are used in SQL query.
