### ISSUE TITLE
$(...).enhancedLovItem is not a function

### ISSUE THREAD

**Issue by aragorniiit** [bostrowski/APEX-Enhanced-Lov-Item#4]
When I run example application in our newly upgraded 19.1 instance, I see below error

$(...).enhancedLovItem is not a function

![image](https://user-images.githubusercontent.com/30124551/56841127-cf408180-6859-11e9-9f93-725f08de6e5d.png)

Please advise.

**Comment by bostrowski** [comment]
@aragorniiit 
The example demo app is valid (tested on apex.oracle.com). If you have upgraded apex I would say you should check ORDS configuration - errors says it can't load file. You can confirm the issue by installing any other valid plugin from apex.world - the error will be same.

**Comment by bostrowski** [comment]
I suggest checking your ORDS configuration.
