### ISSUE TITLE
Enhanced LOV in IG shows result value instead of display value

### ISSUE THREAD

**Issue by Vaysfeld** [bostrowski/APEX-Enhanced-Lov-Item#6]
Hi Bartosz, 
I really like your plugin. But I have problem using it with popup item in IG.  When IG just shows row it shows display value of popup item  - it matches my setting - show only display.  But if I start editing value and select different value it shows result value, only after i save/submit IG row it will show display value. Do I miss something or it is bug? 
Thanks
Vitaliy

**Comment by bostrowski** [comment]
@Vaysfeld 
Interactive Grid support is part of roadmap and potentially it might be available around 2019Q2/2019Q3.
