### ISSUE TITLE
Awesome Plugin, but not supported Arabic search.

### ISSUE THREAD

**Issue by MjAbuhaya** [bostrowski/APEX-Enhanced-Lov-Item#75]

**Comment by MjAbuhaya** [comment]
I found a strange thing when I tested the plugin on apex.oracle, it's working fine with Arabic, but when I tested it on-premise not working !!!.

My question is, Do you think the version is the reason? I asked that, because on premise (22.2.0), but on [http://apex.oracle](https://t.co/mnsC75kn20) (23.1.3).

-- on-premise
![image](https://github.com/Pretius/Pretius-APEX-Enhanced-Lov-Item/assets/76730890/a404d7a1-0a4d-4d15-9b80-4cb07c0bd586)

--apex.oracle
![image](https://github.com/Pretius/Pretius-APEX-Enhanced-Lov-Item/assets/76730890/12974b62-eea1-4215-a1f1-0d759ded10ef)

**Comment by MjAbuhaya** [comment]
I solved the issue, which you need to change NLS to AL32UTF8 using DMU.

**Comment by pstaniszewski** [comment]
Hi,

thank you for your messages and information about the final result.
If you have any additional questions regarding plug-in or APEX development,
feel free to contact me.

Best regards,
Przemek

Przemysław Staniszewski
*Pretius Low-code CEO *
Oracle ACE Pro ♠
mobile:  +48 600800881 <+48+600800881>
site:  www.pretius.com
[image: facebook] <https://www.facebook.com/pretius/>
[image: twitter] <https://twitter.com/pstaniszewski>


*Planned absences/business travels: *

14.09.2023 - No-code Days, Warsaw, Poland

17.09 - 22.09.2023 - CloudWorld, Las Vegas, USA

4.10 - 5.10.2023 - SoDA Conference, Warsaw, Poland

15.11 - 16.11.2023 - UKOUG, Reading, UK

17.11 - 18.11.2023 - POUG, Warsaw, Poland

21.11 - 24.11.2023 - DOAG, Nuremberg, Germany


śr., 6 wrz 2023 o 12:39 MjAbuhaya ***@***.***> napisał(a):
