### ISSUE TITLE
Getting an Info Icon to the right of the field

### ISSUE THREAD

**Issue by jrdad1** [bostrowski/APEX-Enhanced-Lov-Item#8]
I downloaded the APEX Enhanced LOV Item Plugin (1.0.4) from APEX.WORLD and I am getting a button to the right of the item with the fa-info icon on it. When i hover to the button I get "Writes to console autocomplete state". I do not want that button to be displayed. How do I turn it off. I looked at the various settings but could not find it.

**Comment by bostrowski** [comment]
@jrdad1 
Turn off debug mode :-)
